"""Add approval to hours

Revision ID: 0302297c45e2
Revises: 720af6ff73db
Create Date: 2018-03-22 08:56:40.488001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0302297c45e2'
down_revision = '720af6ff73db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hours', sa.Column('approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hours', 'approved')
    # ### end Alembic commands ###
