"""Reimplement reimagined pay cycles

Revision ID: 50f62633e67e
Revises: 352f1a704f19
Create Date: 2018-03-29 21:24:16.981672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy_utils import UUIDType

# revision identifiers, used by Alembic.
revision = '50f62633e67e'
down_revision = '352f1a704f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pay_cycle',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('employee_id', UUIDType(), nullable=True),
    sa.Column('company_id', UUIDType(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paycycle_hours',
    sa.Column('fk_pay_cycle', UUIDType(), nullable=True),
    sa.Column('fk_hours', UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['fk_hours'], ['hours.id'], ),
    sa.ForeignKeyConstraint(['fk_pay_cycle'], ['pay_cycle.id'], )
    )
    op.add_column('employee', sa.Column('pay_cycle_id', UUIDType(), nullable=True))
    op.create_foreign_key(None, 'employee', 'company', ['pay_cycle_id'], ['id'])
    op.drop_column('hours', 'pay_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hours', sa.Column('pay_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'pay_cycle_id')
    op.drop_table('paycycle_hours')
    op.drop_table('pay_cycle')
    # ### end Alembic commands ###
