"""Many to one instead of many to many between pay cycle and hours

Revision ID: 652b758cd43c
Revises: c392e27ab7e2
Create Date: 2018-03-29 21:43:51.418513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy_utils import UUIDType

# revision identifiers, used by Alembic.
revision = '652b758cd43c'
down_revision = 'c392e27ab7e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paycycle_hours')
    op.add_column('hours', sa.Column('pay_cycle_id', UUIDType(), nullable=True))
    op.create_foreign_key(None, 'hours', 'pay_cycle', ['pay_cycle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hours', type_='foreignkey')
    op.drop_column('hours', 'pay_cycle_id')
    op.create_table('paycycle_hours',
    sa.Column('fk_pay_cycle', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('fk_hours', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_hours'], ['hours.id'], name='paycycle_hours_fk_hours_fkey'),
    sa.ForeignKeyConstraint(['fk_pay_cycle'], ['pay_cycle.id'], name='paycycle_hours_fk_pay_cycle_fkey')
    )
    # ### end Alembic commands ###
