"""Change size of password

Revision ID: 720af6ff73db
Revises: d0863240a5c2
Create Date: 2018-03-22 08:11:45.605141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720af6ff73db'
down_revision = 'd0863240a5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    # ### end Alembic commands ###
