"""Fix relations between employee and pay cycles

Revision ID: c392e27ab7e2
Revises: 50f62633e67e
Create Date: 2018-03-29 21:31:41.973746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c392e27ab7e2'
down_revision = '50f62633e67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_pay_cycle_id_fkey', 'employee', type_='foreignkey')
    op.drop_column('employee', 'pay_cycle_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('pay_cycle_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('employee_pay_cycle_id_fkey', 'employee', 'company', ['pay_cycle_id'], ['id'])
    # ### end Alembic commands ###
