"""Add pay date to pay cycle

Revision ID: fd920864e995
Revises: dce5239a0c29
Create Date: 2018-04-18 02:16:37.477047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd920864e995'
down_revision = 'dce5239a0c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pay_cycle', sa.Column('pay_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pay_cycle', 'pay_date')
    # ### end Alembic commands ###
